### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by chilaxan** [chilaxan/Steno#1]

**Comment by AlexSTJO** [comment]
AI-powered waste sorting systems: These systems use computer vision and machine learning algorithms to sort waste into different categories, such as recyclable materials, organic waste, and non-recyclable materials. This can help to improve the efficiency and accuracy of recycling and waste collection processes.

**Comment by AlexSTJO** [comment]
AI-powered waste prediction: These systems use machine learning to predict how much waste will be generated by a community, based on factors such as population density, demographics, and economic activity. This information can be used to plan for the expansion of waste management infrastructure.

**Comment by chilaxan** [comment]
> AI-powered waste sorting systems: These systems use computer vision and machine learning algorithms to sort waste into different categories, such as recyclable materials, organic waste, and non-recyclable materials. This can help to improve the efficiency and accuracy of recycling and waste collection processes.

we could build a physical trashcan and put the sorting device on top

**Comment by AlexSTJO** [comment]
Intelligent Tutoring Systems: These systems use AI to provide personalized feedback and guidance to students, in real-time, as they work through educational content. They can detect when a student is struggling and provide additional support, such as hints, explanations, or additional practice problems.

**Comment by AlexSTJO** [comment]
Predictive analytics for patient care: These systems use machine learning and data analytics to predict patient outcomes and identify those at high risk for complications. This can help to improve patient outcomes by identifying and addressing potential problems early on.

**Comment by AlexSTJO** [comment]
AI-powered diagnostic systems: These systems use machine learning algorithms and image analysis to assist in the diagnosis of diseases. They can help to improve the accuracy of diagnoses and reduce the time it takes to get a diagnosis.

**Comment by adustvenus** [comment]
Offline menu creator:
App - While online, you give it ingredients you have, and it creates menus and meals based on your ingredients. While Offline, you can have saved recipes as well as limited menu creation.
Site - Secondary, gives an overview of the app and how to use, as well as possible website-use of the same functionality. The website would guide you to the 'appstore' page, aka a QR code or similar, to download the app.
ML - Model would need to take in recipes and give out a list of things able to be made

**Comment by XChris923X** [comment]
An AI that can Identify poisonous plants, venom animals

**Comment by adustvenus** [comment]
AI Art generator:
Generator: Using a prompt, the AI would create a piece of digital art, which you could save on your device. You would be allowed a certain number of generations a day, and gain more via the blogpost upvotes.
Blog: A place to share your creations and talk about the pretty pictures. Upvotes on art (no downvotes) means you get more credits because you created dope asf art.
App: ?
NFT: NO just per account or something idk f the blockchain

**Comment by adustvenus** [comment]
Build your own Spacship game:
SBU Hacks OG idea, build your own spaceship then play space invaders with that ship

**Comment by chilaxan** [comment]
Steno woot
